site_name: Obsidian Modal Form docs
repo_url: https://github.com/danielo515/obsidian-modal-form
site_author: Danielo Rodriguez

nav:
    - Home: index.md
    - ResultValue: ResultValue.md
    - Advanced: advanced-examples.md
    - Manging results: managing-results.md

theme:
    name: material
