name: Release

on:
    push:
        branches:
            - master

permissions:
    contents: write
    pull-requests: write

jobs:
    release:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v3

            - name: Install Dependencies
              run: npm ci

            - name: Build
              run: npm run build

            - name: Release Please
              uses: google-github-actions/release-please-action@v3
              id: release
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
                  release-type: node
                  package-name: obsidian-modal-form
                  extra-files: manifest.json
